<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Novolis.Rendering.Planar.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <LibraryReference Include="Novolis.Math.Arrays" />
    <LibraryReference Include="Novolis.Math.Geometry" />
    <LibraryReference Include="Novolis.Math.Topology" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Novolis.Rendering.Planar/Novolis.Rendering.Planar.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="../Novolis.Rendering.Unit/Planar/*.cs" Link="%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
